import os
import tempfile
import unittest

import checksumfile


class ChecksumFileTest(unittest.TestCase):

    def test_that_ultra_iso_checksum_file_can_be_read(self):
        with tempfile.TemporaryDirectory("w") as temp_dir:
            with open(os.path.join(temp_dir, "checksums.txt"), "w") as temp_file:
                temp_file.write("# MD5 checksums generated by UltraISO (http://www.ezbsystems.com)\r\n")
                temp_file.write("# Generated 2024-11-05 14:50:13\r\n")
                temp_file.write("\r\n")
                temp_file.write("d41d8cd98f00b204e9800998ecf8427e *empty.txt\r\n")
                temp_file.write("e2c865db4162bed963bfaa9ef6ac18f0 *some-bytes.dat\r\n")
            checksum_file = checksumfile.read_checksum_file(os.path.join(temp_dir, "checksums.txt"))
            self.assertEqual(checksum_file.type, "UltraISO")
            self.assertEqual(checksum_file.file_checksums["empty.txt"], {"md5": "d41d8cd98f00b204e9800998ecf8427e"})
            self.assertEqual(checksum_file.file_checksums["some-bytes.dat"], {"md5": "e2c865db4162bed963bfaa9ef6ac18f0"})

    def test_that_ultra_iso_checksum_file_is_read_using_win1252_encoding(self):
        with tempfile.TemporaryDirectory("w") as temp_dir:
            with open(os.path.join(temp_dir, "checksums.txt"), "wb") as temp_file:
                temp_file.write(b"# MD5 checksums generated by UltraISO (http://www.ezbsystems.com)\r\n")
                temp_file.write(b"# Generated 2024-11-05 14:50:13\r\n")
                temp_file.write(b"\r\n")
                temp_file.write(b"d41d8cd98f00b204e9800998ecf8427e *empty.txt\r\n")
                temp_file.write("e2c865db4162bed963bfaa9ef6ac18f0 *ümläut.txt\r\n".encode("windows-1252"))
            checksum_file = checksumfile.read_checksum_file(os.path.join(temp_dir, "checksums.txt"))
            self.assertEqual(checksum_file.type, "UltraISO")
            self.assertEqual(checksum_file.file_checksums["empty.txt"], {"md5": "d41d8cd98f00b204e9800998ecf8427e"})
            self.assertEqual(checksum_file.file_checksums["ümläut.txt"], {"md5": "e2c865db4162bed963bfaa9ef6ac18f0"})

if __name__ == '__main__':
    unittest.main()
